import config
print("ENABLE_LIVE_TRADING:", config.ENABLE_LIVE_TRADING)
print("SCAN_PROFILE:", config.SCAN_PROFILE)
print("POLICY_VERSION:", config.CURRENT_POLICY_VERSION)
print("CLASSIFIER_VERSION:", config.CLASSIFIER_VERSION)
print("UNIVERSE:", config.TOP_N_PAIRS)
print("BURST_ACTIVE:", config.TEMP_DATA_BURST_ACTIVE)
